version: '3.5'
networks:
  app-staffing-backend-network: {}
services:
  db:
    container_name: app-staffing-backend-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
        - ./initdb-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    networks:
      - app-staffing-backend-network

  api:
    container_name: app-staffing-backend-api
    depends_on:
      - db
    volumes: 
      - ./src:/usr/src/app/src
      - ./db:/usr/src/app/db
      - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: 3000
      DATABASE_CONNECTION_STRING: postgres://dbuser:dbpassword@db:5432/staffing
    ports:
      - 3000:3000
      - 9229:9229
    command: tail -f /dev/null
    # command: >
    #   sh -c '\
    #     npm i -g nodemon \
    #     && npm run migrate \
    #     && npm run seed \
    #     && nodemon --inspect=0.0.0.0:9229 src/app.js
    #   '
    networks:
      - app-staffing-backend-network
