{{- if and .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $val := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    chart: {{ .Chart.Name }}
{{- end }}