name: Deploy VM Dev

on:
  push:
    branches: [ vm-deploy-dev ]

permissions:
  contents: read

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      # uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.3
      uses: bitovi/github-actions-deploy-docker-to-ec2@77-data-source-for-domain-certificate-should-not-be-called-if-no-domain-is-provided
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}

        app_port: 4000